config/routes.rb
Fstvl::Application.routes.draw do
  
  resources :countries

  resources :acts
  resources :prices
  resources :festivals

  root :to => 'festivals#index'

  match '/import' => "festivals#import"  
  match '/monthsums' => "festivals#monthsums"    

end

app/views/layouts/_toppromo.html.erb
<div id="topPromo">
	
	<div id="clouds">
        <ul id="cloud-group-1">
            <li class="cloud-1"></li>
            <li class="cloud-2"></li>
            <li class="cloud-3"></li>
        </ul>
        <ul id="cloud-group-2">
            <li class="cloud-1"></li>
            <li class="cloud-2"></li>
            <li class="cloud-3"></li>
        </ul>
        <ul id="cloud-group-3">
            <li class="cloud-4"></li>
        </ul>
    </div>

	<canvas id="pixie" style="position:relative; top: 100px; z-index: 0;"></canvas>

	<!-- <div id="fstvlLogo"> </div> -->

</div>

<script type="text/javascript">

	var WIDTH;
	var HEIGHT;
	var canvas;
	var con;
	var g;
	var pxs = new Array();
	var rint = 60;

	$(document).ready(function(){
		
		var container = $('#topPromo')
		
		WIDTH = container.width();
		HEIGHT = container.height() / 2;
		
		$('#container').width(WIDTH).height(HEIGHT);
		canvas = document.getElementById('pixie');
		$(canvas).attr('width', WIDTH).attr('height',HEIGHT);
		con = canvas.getContext('2d');
		for(var i = 0; i < 30; i++) {
			pxs[i] = new Circle();
			pxs[i].reset();
		}
		setInterval(draw,rint);

	});

	function draw() {
		con.clearRect(0,0,WIDTH,HEIGHT);
		for(var i = 0; i < pxs.length; i++) {
			pxs[i].fade();
			pxs[i].move();
			pxs[i].draw();
		}
	}

	function Circle() {
		
		this.s = { ttl:12000, xmax:3, ymax:2, rmax:4, rt:1, xdef:960, ydef:540, xdrift:4, ydrift: 4, random:true, blink:true };

		this.reset = function() {
			this.x = (this.s.random ? WIDTH*Math.random() : this.s.xdef);
			this.y = (this.s.random ? HEIGHT*Math.random() : this.s.ydef);
			this.r = ((this.s.rmax-1)*Math.random()) + 1;
			this.dx = (Math.random()*this.s.xmax) * (Math.random() < .5 ? -1 : 1);
			this.dy = (Math.random()*this.s.ymax) * (Math.random() < .5 ? -1 : 1);
			this.hl = (this.s.ttl/rint)*(this.r/this.s.rmax);
			this.rt = Math.random()*this.hl;
			this.s.rt = Math.random()+1;
			this.stop = Math.random()*.2+.4;
			this.s.xdrift *= Math.random() * (Math.random() < .5 ? -1 : 1);
			this.s.ydrift *= Math.random() * (Math.random() < .5 ? -1 : 1);
		}

		this.fade = function() {
			this.rt += this.s.rt;
		}

		this.draw = function() {
			if(this.s.blink && (this.rt <= 0 || this.rt >= this.hl)) this.s.rt = this.s.rt*-1;
			else if(this.rt >= this.hl) this.reset();
			var newo = 1-(this.rt/this.hl);
			con.beginPath();
			con.arc(this.x,this.y,this.r,0,Math.PI*2,true);
			con.closePath();
			var cr = this.r*newo;
			g = con.createRadialGradient(this.x,this.y,0,this.x,this.y,(cr <= 0 ? 1 : cr));
			g.addColorStop(0.0, 'rgba(255,255,255,'+newo+')');
			g.addColorStop(this.stop, 'rgba(155,155,155,'+(newo*.6)+')');
			g.addColorStop(1.0, 'rgba(255,255,255,0)');
			con.fillStyle = g;
			con.fill();
		}

		this.move = function() {
			this.x += (this.rt/this.hl)*this.dx;
			this.y += (this.rt/this.hl)*this.dy;
			if(this.x > WIDTH || this.x < 0) this.dx *= -1;
			if(this.y > HEIGHT || this.y < 0) this.dy *= -1;
		}

		this.getX = function() { return this.x; }
		this.getY = function() { return this.y; }
	}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
	<meta name="description" content="xx">	
	
  	<title>Fstvl</title>

  	<%= stylesheet_link_tag "application", "fstvl1", "fstvl2", "animations" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
	<script type="text/javascript" src="http://use.typekit.com/ffl5rel.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
	<!--[if lt IE 9]><script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>

<body>

	<header>
		<nav id="main">
			<a href="/" id="logo">FSTVL</a>
			<a href="/x" ><strong>Contact</strong><em>let's work together</em></a>
			<a href="/y"><strong>Contact</strong><em>let's work together</em></a>		
		</nav>
	</header>
	
	<div id="subhead">
		<nav>
			<ul>
				<li><%= link_to "Festivals", festivals_url %></li>
				<li><%= link_to "Acts", acts_url %></li>
			</ul>
			<input type="text" size="30" name="search[blurb_like]" id="search" class="smartInput">		
		</nav>		
	</div>
	
	<% if controller.controller_name == 'festivals' && controller.action_name == 'index' %>
		<%= render 'layouts/toppromo' %>
	<% end %>

	<section id="content">
		<%= yield %>
	</section>
	
	<!--
	<div id="bottomPromo">
		<div class="miniPromo"></div><div class="miniPromo"></div><div class="miniPromo"></div><div class="miniPromo"></div>
	</div>
	-->
	
	<div id="bottomAdContainer">
		<div id="bottomAd">
			<script type="text/javascript"><!--
			google_ad_client = "ca-pub-6918447094199276";
			/* Fstvl */
			google_ad_slot = "5419633632"; google_ad_width = 728; google_ad_height = 90;
			//-->
			</script>
			<script type="text/javascript"src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
		</div>
	</div>
	
	<footer>
		<article role="about">
			<small>&copy; 2012 <a href="http://www.larsattacks.co.uk">LA</a></small>
		</article>
	</footer>
	
</body>

</html>