config/routes.rb
Fstvl::Application.routes.draw do
  
  resources :countries

  resources :acts
  resources :prices
  resources :festivals

  root :to => 'festivals#index'

  match '/import' => "festivals#import"  
  match '/monthsums' => "festivals#monthsums"    

end

app/models/act.rb
class Act < ActiveRecord::Base
  
  has_and_belongs_to_many :festivals
  
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController

  def index
    @acts = Act.all.sort { |a,b| a.name <=> b.name }
    @groupedActs = @acts.group_by { |i| i.name[0..0] }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @acts }
    end
  end

  def show
    @act = Act.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @act }
    end
  end

  def new
    @act = Act.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @act }
    end
  end


  def edit
    @act = Act.find(params[:id])
  end

  def create
    @act = Act.new(params[:act])

    respond_to do |format|
      if @act.save
        format.html { redirect_to @act, notice: 'Act was successfully created.' }
        format.json { render json: @act, status: :created, location: @act }
      else
        format.html { render action: "new" }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /acts/1
  # PUT /acts/1.json
  def update
    @act = Act.find(params[:id])

    respond_to do |format|
      if @act.update_attributes(params[:act])
        format.html { redirect_to @act, notice: 'Act was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acts/1
  # DELETE /acts/1.json
  def destroy
    @act = Act.find(params[:id])
    @act.destroy

    respond_to do |format|
      format.html { redirect_to acts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/views/acts/_form.html.erb
<%= form_for(@act) do |f| %>
  <% if @act.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h2>

      <ul>
      <% @act.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <!--%= f.label :festival_id %><br /-->
    <!--%= f.number_field :festival_id %-->
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acts/edit.html.erb
<div id="actsPage">
	<h2>Editing act</h2>

	<%= render 'form' %>

	<%= link_to 'Show', @act %> |
	<%= link_to 'Back', acts_path %>
</div>

app/views/acts/index.html.erb
<div id="actsPage">
	<h2>Acts</h2>
	
	<div class="col">
	<% @groupedActs.each_with_index do |group,i| %>
	
			<ul class="acts">
				<li class="header"><%= group[0] %></li>
				<% group[1].each_with_index do |t,i| %>
					<li><%= link_to t.name, t %></li>		
				<% end %>
			</ul>	
		<% if i%5 == 2; %>
			</div><div class="col">
		<% end %>	
			
	<% end %>
	</div>	
</div>

app/views/acts/new.html.erb
<div id="actsPage">
	<h2>New act</h2>
	<%= render 'form' %>
	<%= link_to 'Back', acts_path %>
</div>

app/views/acts/show.html.erb
<div id="actsPage">
	<h2><%= @act.name %></h2>

	<p id="notice"><%= notice %></p>

	<p>
	  <b>Name:</b>
	  <%= @act.name %>
	</p>

	<% @act.festivals.each do |festival| %>
		<div><%= link_to festival.title, festival %>
	<% end %>

	<br/>

	<%= link_to 'Edit', edit_act_path(@act) %> |
	<%= link_to 'Back', acts_path %>
</div>